### ISSUE TITLE
add Altro ERROR

### ISSUE THREAD

**Issue by xinsongyan** [RoboticExplorationLab/Altro.jl#11]
I am new to julia, when I tried to add Altro.jl, I got the error as shown below:

(@JuliaPro_v1.5.2-1) pkg> add Altro
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Rotations [6038ab10]:
 Rotations [6038ab10] log:
 ├─possible versions are: [0.7.2, 0.8.0, 0.9.0-0.9.2, 0.10.0, 0.11.0-0.11.1, 0.12.0-0.12.1, 0.13.0, 1.0.0-1.0.1] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.7.2, 0.8.0, 0.9.0-0.9.2, 0.10.0, 0.11.0-0.11.1, 0.12.0-0.12.1, 0.13.0, 1.0.0-1.0.1]
 ├─restricted by compatibility requirements with Altro [5dcf52e5] to versions: 1.0.0-1.0.1
 │ └─Altro [5dcf52e5] log:
 │   ├─possible versions are: [0.1.0, 0.2.0] or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions [0.1.0, 0.2.0]
 └─restricted by compatibility requirements with RigidBodyDynamics [366cf18f] to versions: [0.7.2, 0.8.0, 0.9.0-0.9.2, 0.10.0, 0.11.0-0.11.1, 0.12.0-0.12.1, 0.13.0] — no versions left
   └─RigidBodyDynamics [366cf18f] log:
     ├─possible versions are: [0.0.1-0.0.6, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.1, 0.7.0, 0.8.0, 0.9.0, 1.0.0-1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 2.0.0, 2.1.0-2.1.1, 2.2.0] or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.6, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.1, 0.7.0, 0.8.0, 0.9.0, 1.0.0-1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 2.0.0, 2.1.0-2.1.1, 2.2.0]
     ├─restricted by compatibility requirements with MechanismGeometries [931e9471] to versions: [0.5.0, 0.6.0-0.6.1, 0.7.0, 0.8.0, 0.9.0, 1.0.0-1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 2.0.0, 2.1.0-2.1.1, 2.2.0]
     │ └─MechanismGeometries [931e9471] log:
     │   ├─possible versions are: [0.1.0-0.1.2, 0.2.0, 0.3.0, 0.4.0-0.4.1, 0.5.0] or uninstalled
     │   └─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.2, 0.2.0, 0.3.0, 0.4.0-0.4.1, 0.5.0]
     ├─restricted by compatibility requirements with RigidBodySim [e61f16d8] to versions: [0.6.0-0.6.1, 0.7.0, 0.8.0, 0.9.0, 1.0.0-1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 2.0.0, 2.1.0-2.1.1, 2.2.0]
     │ └─RigidBodySim [e61f16d8] log:
     │   ├─possible versions are: [0.3.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0] or uninstalled
     │   └─restricted to versions * by an explicit requirement, leaving only versions [0.3.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0]
     └─restricted by compatibility requirements with StaticArrays [90137ffa] to versions: [1.2.0, 1.3.0, 1.4.0, 2.0.0, 2.1.0-2.1.1, 2.2.0] or uninstalled, leaving only versions: [1.2.0, 1.3.0, 1.4.0, 2.0.0, 2.1.0-2.1.1, 2.2.0]
       └─StaticArrays [90137ffa] log:
         ├─possible versions are: [0.8.0-0.8.3, 0.9.0-0.9.2, 0.10.0, 0.10.2-0.10.3, 0.11.0-0.11.1, 0.12.0-0.12.5] or uninstalled
         ├─restricted to versions * by an explicit requirement, leaving only versions [0.8.0-0.8.3, 0.9.0-0.9.2, 0.10.0, 0.10.2-0.10.3, 0.11.0-0.11.1, 0.12.0-0.12.5]
         └─restricted by compatibility requirements with Altro [5dcf52e5] to versions: 0.12.0-0.12.5
           └─Altro [5dcf52e5] log: see above

**Comment by xinsongyan** [comment]
The problem is that I have RigidBodyDynamcis installed. Altro uses RobotDynamics.

**Comment by bjack205** [comment]
Yeah, we haven't synced up these repos yet. You can usually avoid these dependency issues by installing packages in a clean Julia environment.
