### ISSUE TITLE
Solver Stats Index Error

### ISSUE THREAD

**Issue by tpunnoose** [RoboticExplorationLab/Altro.jl#4]
I get a `BoundsError: attempt to access 1000-element Array{Float64,1} at index [0]` originating at the following line:
https://github.com/RoboticExplorationLab/Altro.jl/blob/ee66cb0b94e3d2a044cd74a72cbd161b0fd45072/src/augmented_lagrangian/al_methods.jl#L83

**Comment by tpunnoose** [comment]
A similar error `ERROR: BoundsError: attempt to access 1000-element Array{Int64,1} at index [0]` here:
https://github.com/RoboticExplorationLab/Altro.jl/blob/e48a4337db72174be3ac19b1665bf3075c2688ba/src/solver_opts.jl#L198

**Comment by bjack205** [comment]
Can you give some more background on how you generated this error? The only way this should happen is if you have 0 iLQR iterations and then attempt an outer loop iteration. I can put a safeguard to prevent this error, but I'm curious as to how it's even doing this. In particular, can you check if `solver.stats.status == SOLVE_SUCCEEDED`? This the only way I could getting this error, but it's still odd. Are you solving the same problem again, like a warm start? If so, there could a problem with resetting the solver.
