### ISSUE TITLE
status bound constraint

### ISSUE THREAD

**Issue by ZeeCarl** [RoboticExplorationLab/ALTRO.jl#50]
thank you for provide this package,
does it  provide a  current  interface of set a status bound constraint like goal constraint and control constraint?

**Comment by ZeeCarl** [comment]
@bjack205

**Comment by bjack205** [comment]
Control and state bounds are both supported, as well as general nonlinear constraints, as long as they are stage-wise.

**Comment by ZeeCarl** [comment]
> Control and state bounds are both supported, as well as general nonlinear constraints, as long as they are stage-wise.

thank u for reply, I have finished state constraints  by using altro-cpp,
it seems that control bound and state bound won't work when bound trajectory infeasible,

now i'm working to add the rate of control bound into my project , like jerk in a unicycle model(state：x,y,theta,v and control:front_wheel_angle, rear_wheel_acceleration),
can you show me some ideas?  @bjack205
