### ISSUE TITLE
ALconset.jl required

### ISSUE THREAD

**Issue by serenity4** [RoboticExplorationLab/Altro.jl#8]
Hi,

The ALconset.jl file was removed from TrajectoryOptimization, to be added to Altro (according to [this commit](https://github.com/RoboticExplorationLab/TrajectoryOptimization.jl/commit/5584984cd472d5ceb6634c032b8b572e57754084)), but no changes were made to Altro and it errors when it tries to import ALconset from TrajectoryOptimization. Is there a commit in progress to fix this?

**Comment by bjack205** [comment]
Yes, this is a WIP. It's working on a branch right now but hasn't been merged to master yet. You can always specify the previous version of TrajectoryOptimization that included that file.

**Comment by serenity4** [comment]
Ok, thanks.
